""" Problem 12: Highly Divisible Triangular Number

https://projecteuler.net/problem=12

Goal: Find the value of the first triangle number to have more
than N divisors.

Constraints: 1 <= N <= 1e3

Triangle Number: a number generated by adding all natural numbers
prior to & including itself.

e.g.: N = 5
      1st = 1 from [1] -> {1}
      2nd = 3 from [1+2] -> {1,3}
      3rd = 6 from [1+2+3] -> {1,2,3,6}
      4th = 10 from [1+2+3+4] -> {1,2,5,10}
      5th = 15 from [1+2+3+4+5] -> {1,3,5,15}
      6th = 21 from [1+2+3+4+5+6] -> {1,3,7,21}
      7th = 28 from [1+2+3+4+5+6+7] -> {1,2,4,7,14,28}
      result = 28
"""